# -*- coding: utf-8 -*-
import csv
import subprocess
#log management
import sys
import time
import datetime


#########################################################################
# http://www.nltk.org/book/ch07.html Chunker & Relation Extractions     #
# The inputs are the CSV generated by the scrapy spiders                #
# The output will be a CSV file with the fields to introduce in DB      #
#########################################################################

#Opening log file and routing the stdout and stderr
saveout = sys.stdout
fsock = open('/home/quique/labo/eacopenlist/eacopenlistbot/log/chunker_rel_extractor.log', 'a')
sys.stdout = fsock
sys.stderr = fsock

#Opening all the CSV files at the work directory
csv_list = subprocess.call('ls /home/quique/labo/eacopenlist/eacopenlistbot/*.csv', shell=True, )
for csv_file in csv_list:
    csv_input = csv.reader(file(csv_file))
    for row in csv_input:
